### PR TITLE
convert all view copy to i18n for internationalization

### LINKED ISSUE #69: Convert text copy to i18n internationalization

### PR DESCRIPTION
**Pull request by mejackreed**
Closes #69

### CODE REVIEW

**Review by versae — COMMENTED** [review]
Awesome! Question, would it be too awful to have the actual English text as keys in the YAML? That way we could reuse same text when needed, and also have more legible views. I am aware this might not be the Rails way of doing things, but I had to ask.

I was even thinking about having some sort of rake command to compile the `en.yml` for us.

**Comment by mejackreed** [comment]
I'm not exactly sure what you mean. Could you post an example?

**Comment by versae** [comment]
Yep, I mean that instead of having things like
```ruby
t('navigation.next_step')
t 'image_templates.title'
```
Which makes sense but is a bit cryptic and we might run out of names fast, we could have
```ruby
t('Next Step')
t 'Create image templates'
```
And in the `en.yml` would be something like
```yaml
en:
 - 'Next Step': 'Next Step'
 - 'Create Image Templates': 'Create Image Templates'
```
But not sure if this would work. I am just thinking out loud.

**Comment by mejackreed** [comment]
@versae yep that approach would work. I've only used the approach that I implemented (we use that in Blacklight/Hydra/GeoBlacklight), but am willing to change it up.

What do you think?

**Comment by versae** [comment]
No, that's OK, why change something that is proven to work, right? :)

**Review by versae — APPROVED** [review]

**Comment by mejackreed** [comment]
/shrug.. i like your idea though

**Pull request merged**
