### PR TITLE
[WIP] adds cropper and closes #52

### LINKED ISSUE #52: Populate form from cropper events.

### PR DESCRIPTION
**Pull request by aeschylus**

### CODE REVIEW

**Comment by aeschylus** [comment]
How/where do I write a test for this?

**Comment by mejackreed** [comment]
@aeschylus would you like to pair on writing the tests for this today?

**Comment by aeschylus** [comment]
@mejackreed that would be helpful for me.

**Comment by csbailey5t** [comment]
@aeschylus and @mejackreed Is this PR waiting for tests and style fixes before being considered for merging?

**Comment by mejackreed** [comment]
Yep, I'm going to throw a [WIP] (work in progress) tag on it. I think @aeschylus is redoing some aspects of it.

**Comment by csbailey5t** [comment]
Cool. I just pulled it to check it out and am running into a couple of issues. The image is not actually being shown within the cropper. Is that supposed to be the case at the moment? I'm also getting this error on the cropper page:  `Uncaught SyntaxError: Unexpected end of input  crop_image:59`, which might be why an image isn't being shown.

**Comment by mejackreed** [comment]
Yep we discussed that I think part of it was going to be reincorporated as a React component similar to the work done in the other component.

**Comment by csbailey5t** [comment]
This is now handled in #88

**Pull request closed without merging**
