### PR TITLE
Add collection views

### LINKED ISSUE #145: Add CRUD for collections
- [x] Index for collections
- [x] New collection 
- [x] Edit collection
- [x] Delete collection
- [x] Show collection
- [x] en.yml for all ui text
- [x] Tests

### PR DESCRIPTION
**Pull request by csbailey5t**
Fixes #145 

This doesn't perfectly match the design docs, but it does establish basic CRUD for collections with associated views. From here, as we build out features, we can modify as needed.

### CODE REVIEW

**Comment by csbailey5t** [comment]
I've fixed all the hound violations except for the too many lines in a block and the array of symbols. For the latter, we use the syntax I've used elsewhere, and for the former, I'm not sure how to break up that block more effectively.

**Comment by versae** [comment]
For the block length, we could add [`.hound.yml`](https://github.com/sul-cidr/histonets/blob/master/.hound.yml) and [`.rubocop.yml`](https://github.com/sul-cidr/histonets/blob/master/.rubocop.yml) files.

**Comment by csbailey5t** [comment]
I can do a separate PR that adds those. That way we can keep it separate from this PR.

**Review by versae — COMMENTED** [review]
Nice! Starting to take form.

Question, should the collection show view display the list of images of that collection?

**Comment by csbailey5t** [comment]
@versae It should eventually, but it seems like the images don't have a foreign key for the collection yet, so we can't get the images attached to a collection. I have an issue in for showing all the images attached to a collection on the show view.

**Review by versae — APPROVED** [review]
👍

**Pull request merged**
